### ISSUE TITLE
Create "file list block" which works like File Block but supports multiple files

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-elemental-fileblock#1]
@wilr commented on [Thu Oct 12 2017](https://github.com/silverstripe/silverstripe-elemental-blocks/issues/2)

---

@robbieaverill commented on [Wed Oct 18 2017](https://github.com/silverstripe/silverstripe-elemental-blocks/issues/2#issuecomment-337366938)

@clarkepaul, are we going to do it this way or create a different block?

---

@clarkepaul commented on [Wed Oct 18 2017](https://github.com/silverstripe/silverstripe-elemental-blocks/issues/2#issuecomment-337489326)

"Image block" is singular upload and only accepts images, this is the one that banner feeds off. 

The other blocks which are not part of the first sprint:
"File list block" needs multi upload
"Media block" needs singular upload (used for displaying video, audio etc.) but not part of core yet.

---

@robbieaverill commented on [Wed Oct 18 2017](https://github.com/silverstripe/silverstripe-elemental-blocks/issues/2#issuecomment-337514705)

Ok, we should go through at some stage and log these all as new enhancement issues.

---

@robbieaverill commented on [Fri Oct 27 2017](https://github.com/silverstripe/silverstripe-elemental-blocks/issues/2#issuecomment-339840267)

Renamed

---

@michalkleiner commented on [Tue Jan 09 2018](https://github.com/silverstripe/silverstripe-elemental-blocks/issues/2#issuecomment-356150421)

Wouldn't it be better to just allow the file block to hold multiple files (and optionally rename it)? The number of files can be limited within the upload field config if needed.

---

@robbieaverill commented on [Tue Jan 09 2018](https://github.com/silverstripe/silverstripe-elemental-blocks/issues/2#issuecomment-356152218)

>Wouldn't it be better to just allow the file block to hold multiple files (and optionally rename it)? The number of files can be limited within the upload field config if needed.

I think that would be easier from a development perspective, but it might not be from a UX perspective. I'll leave this to @clarkepaul and @sachajudd to decide, but I think this is part of a future scope for the content blocks work that SS Ltd. has been doing.
  

---

@clarkepaul commented on [Mon Jan 15 2018](https://github.com/silverstripe/silverstripe-elemental-blocks/issues/2#issuecomment-357580136)

A "File list block" is a list of links to files while a "Image block" displays as a visual element rather than a link. I think its best to keep them as separate blocks. It might be that there could be a multi file block where you could decide on how its displayed (eg. list of links, as a gallery) but that hasn't been discussed as far as I know—I think it would make more sense to have these as two separate blocks.

**Comment by korthjp17** [comment]
Just curious to see if anything is still being planned for this feature? We have a site that we would like to do something similar with multiple files in a list.

**Comment by robbieaverill** [comment]
@korthjp17 it's not on the immediate roadmap, but if you end up creating something for your client and want to open source it we can close this and link to it from the readme/the elemental readme =)

**Comment by korthjp17** [comment]
Sounds good. We were talking about that internally - I think that's the route we were going to go, but wasn't sure if anyone had started working on this locally. Thanks!

**Comment by korthjp17** [comment]
@robbieaverill and anyone else that's interested - We came up with a solution that seems to work for this. If you have a second to take a look, this is what we are using: https://github.com/dynamic/silverstripe-elemental-filelist

**Comment by michalkleiner** [comment]
@korthjp17 probably better as an issue at your end, but as you've posted it here - what's the reason to have the middle-layer FileListObject holding the File instead of directly having has_many Files?

**Comment by jsirish** [comment]
@michalkleiner the primary reason we did a FileListObject layer is because the CMS fields for adding a File directly were non-optimal - no UploadField, a read only file path TextField, etc. Rather than applying a DataExtension to File, or extending File, it made sense to us to extend DataObject with has_one File. 

We'd be open to an adjustment if anyone knows a better way to add a File directly via GridField. We've only used this on one in-progress project and could write a migrator in that case.

**Comment by SharronRobins** [comment]
@jsirish  I am using silverstripe-elemental-filelist in my project. It works for our school newsletters (pdf uploads) but would be better if I could upload multiple files at once and have drag and drop ordering any ideas?

**Comment by robbieaverill** [comment]
Hi everyone, as of #10 we've made it explicit that this module only allows a single file to be uploaded into the block. In terms of this issue, I think it'd be best for somebody to create a new module to handle multiple, or use the one that @jsirish pointed out at https://github.com/dynamic/silverstripe-elemental-filelist. Thanks!
