### ISSUE TITLE
In-line UploadField appears to take multiple files when this block only supports one

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-elemental-fileblock#10]
### Affected Version

2.0.x

### Description

Using the upload field in the new in-line edit form for this block seems to allow for multiple files but the block itself doesn't actually support that.

### Steps to reproduce

- Create a file block in an elemental area
- Use the upload form and add multiple files/images
- Note that only one is actually saved

cc @sachajudd

**Comment by robbieaverill** [comment]
I can't reproduce - it only lets me select one file from the upload dialog, or one from the assets gallery

cc @ScopeyNZ @sachajudd

**Comment by robbieaverill** [comment]
Lol - I didn't read the version 🤦‍♂️

**Comment by robbieaverill** [comment]
Fix at #12
