### ISSUE TITLE
Stable version shouldn't require dev dependencies

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-elemental-fileblock#23]
The `"dnadesign/silverstripe-elemental": "^4@dev"` requirement is causing issues for my project which, wherever possible, is using stable dependencies. Is there a reason this is specifically set to use the branch instead of having a stable dependency?

**Comment by ChloeSartorelli** [comment]
Nevermind, it wasn't the @dev that was causing my problems afterall. Closing.
