### ISSUE TITLE
Inline editing of File Block

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-elemental-fileblock#3]
## User Story

As a CMS user, I want to be able to edit the contents of a file list block within a page context, so that I can edit the block more efficiently.

## Acceptance Criteria

- [x] The block can be expanded and collapsed
- [x] The editable features currently available for a file list block are present for inline editing, including:
  - Title (and a checkbox to display or hide it)
  - Files section allowing user to upload a file via Browse or Add from files
- [x] A list of files selected to be included in the block are displayed.
- [x] Files that have been successfully uploaded display a green tick to the user.
- [ ] The following information is displayed in the file list for each file:
  - Thumbnail image
  - File name
  - File size
  - File type
- [x] Clicking ‘Save’ at the page level saves the current content entered in the block.
- [x] Clicking ‘Publish’ at the page level publishes the current content entered in the block.
- [x] Styling as per wireframe: https://projects.invisionapp.com/share/ZRL4T2HQAGB#/screens/301923216

**Comment by brynwhyman** [comment]
The bulk of inline editing work will likely cover the ACs covered here. Wait for the below to be complete before proceeding with this issue:
https://github.com/dnadesign/silverstripe-elemental/issues/295

**Comment by ScopeyNZ** [comment]
This is done using the standard `UploadField` component provided by `silverstripe-admin`. If there's more to do here let's raise supplementary issues 🙂
