### ISSUE TITLE
HTML showing in inline preview

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-elemental-fileblock#39]
Happens in CMS 5, doesn't happen in CMS 4

![image](https://github.com/silverstripe/silverstripe-elemental-fileblock/assets/4809037/9d8f9cb6-d8e5-4188-b1be-45456ea0ff78)

Replicate steps:
- Create a new file block
- Upload a new image
- Save the page

## PRs
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/116
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/42
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/43
- https://github.com/silverstripe/developer-docs/pull/300

**Comment by ChloeSartorelli** [comment]
This is happening because `getSummary()` is actually being used now, where in CMS 4 it wasn't. The summary should just be a plain-text summary.

**Comment by sabina-talipova** [comment]
We should probably remove the `FileBlock::getSummaryThumbnail` method and `SummaryThumbnail.ss` template file in the future as they are no longer needed.
**Update:** If you check `Summary` Component in `silverstripe-elemental` you will see that there are no ways how to set HTML Elements and probably any HTML will be redundant there.

**Comment by ChloeSartorelli** [comment]
Bug fixes tagged on [fileblock](https://github.com/silverstripe/silverstripe-elemental-fileblock/releases/tag/3.0.2) and [bannerblock](https://github.com/silverstripe/silverstripe-elemental-bannerblock/releases/tag/3.0.2) respectively as 3.0.2

**Comment by ChloeSartorelli** [comment]
All PRs merged
