### ISSUE TITLE
Unable to edit in-line if block was empty when created

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-elemental-fileblock#5]
If a file block is created from GridFieldDetailForm without any content, when the user attempts to expand the block for in-line editing, the block does not expand. Expected behaviour is the block should expand and allow the user to add content.

Steps to recreate:
1. Add File block to page
2. Create File block with no content
3. Attempt to expand the block for editing in edit mode
4. Identify that block does not expand

**Comment by raissanorth** [comment]
Closed via https://github.com/dnadesign/silverstripe-elemental/pull/444/commits
