### ISSUE TITLE
Error message when adding large files via inline editing are not readable

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-elemental-fileblock#9]
### Reproduce

1. Install `silverstripe/elemental-fileblock` on `2.x-dev` and  `dnadesign/silverstripe-elemental` on        `4.x-dev`
2. Create a page that has the ElementalPageExtension enabled
3. Add a FileBlock via the Add Block button
4. Click on the newly created File Block to expand it
5. Use the `Browse` link to add a file that is 2MB+
6. Observe an truncated error message as shown below

![image](https://user-images.githubusercontent.com/14869519/47880099-340cb780-de87-11e8-9669-5add90850b0e.png)

7. Hover over the error message and see that the tooltip does not show the entire message either

**Comment by raissanorth** [comment]
@clarkepaul @newleeland Any thoughts on this one, please?!

**Comment by clarkepaul** [comment]
I think we need to provide additional designs, I'll add it to our to do list. I would say it's better that we just show the message across the top of the item, but in the mean time if anyone gets around to it they could add a tooltip to the message as a MVP. In the instance pictured above we don't need the space where the image thumb is so everything could move over a bit.

**Comment by robbieaverill** [comment]
I'm going to close this because it should be handled in core - this isn't specific to elemental

**Comment by robbieaverill** [comment]
Moved to https://github.com/silverstripe/silverstripe-admin/issues/745
